name: mi_card_flutter
description: Mi Card Flutter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
     - images/photo1.jpeg

  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf

  - family: OpenSans
    fonts:
      - asset: fonts/OpenSans-Regular.ttf